# Generated by Django 5.1.1 on 2024-10-29 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_first_name_user_last_name_user_nickname"),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_number", models.CharField(max_length=16, unique=True)),
                (
                    "card_type",
                    models.CharField(
                        choices=[("Visa", "Visa"), ("MasterCard", "MasterCard")],
                        editable=False,
                        max_length=10,
                    ),
                ),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("added_on", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
