# Generated by Django 5.1.1 on 2024-10-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historyimage",
            name="history",
        ),
        migrations.RemoveField(
            model_name="historytext",
            name="history",
        ),
        migrations.AddField(
            model_name="history",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="history"),
        ),
        migrations.DeleteModel(
            name="HistoryFile",
        ),
        migrations.DeleteModel(
            name="HistoryImage",
        ),
        migrations.DeleteModel(
            name="HistoryText",
        ),
    ]
